export const USER         = 'user'
export const LOGIN        = 'login'
export const SIGNUP       = 'signup'
export const MOVIE        = 'movie'
export const TV           = 'tv'
export const POPULAR      = 'popular'
export const TOP_RATED    = 'top_rated'
export const UPCOMING     = 'upcoming'
export const NOW_PLAYING  = 'now_playing'
export const AIRING_TODAY = 'airing_today'
export const ON_THE_AIR   = 'on_the_air'

